---
- name: Add flux PPA
  apt_repository: repo='ppa:nathan-renniewaldock/flux'
  
- name: Install libraries with apt
  sudo: false
  apt: name={{ item }} state=latest
  with_items:
    - silversearcher-ag # for quickly searching for files (including contents)
    - encfs # for encrypting directories
    - ffmpeg 
    - git
    - vim
    - scala
    - tmux
    - tree
    - youtube-dl
    - lame
    - fluxgui
    - network-manager-openvpn
    - glipper
    - transmission-gtk
    - build-essential checkinstall
    - libssl-dev
    - calibre
    - vagrant
    - virtualbox
    - virtualenv
    - direnv
    - maven
    - compizconfig-settings-manager
    - compiz-plugins
    #- nodejs # do I want this? or do I want to use nvm, or the repository maintained by the nvm guys. See https://wiki.archlinux.org/index.php/Full_system_backup_with_rsync, but keep in mind that you need a global install of nodejs to make tern work: https://github.com/ternjs/tern_for_vim

#todo: install unrar
#todo: heroku
#todo: git-extras
