---
- name: Install libraries with apt
  sudo: false
  apt: name={{ item }} state=latest
  with_items:
    - silversearcher-ag # for quickly searching for files (including contents)
    - encfs # for encrypting directories
    - ffmpeg 
    - git
    - vim
    - scala
    - tmux
    - tree
    - youtube-dl
    - lame

#todo: install vcprompt https://github.com/djl/vcprompt
#todo: install unrar
#todo: heroku
