---
- name: Add flux PPA
  apt_repository: repo='ppa:nathan-renniewaldock/flux'
  
- name: Install libraries with apt
  sudo: false
  apt: name={{ item }} state=latest
  with_items:
    - silversearcher-ag # for quickly searching for files (including contents)
    - encfs # for encrypting directories
    - ffmpeg 
    - git
    - vim
    - scala
    - tmux
    - tree
    - youtube-dl
    - lame
    - fluxgui
    - network-manager-openvpn
    - glipper
    - transmission-gtk
    - build-essential checkinstall
    - libssl-dev
    - calibre
    - vagrant
    - virtualbox
    - virtualenv
    - direnv
    - maven
    - compizconfig-settings-manager
    - compiz-plugins

- name: Install node dependancies
  sudo: true

#todo: install unrar
#todo: heroku
