---
- name: Test Go
  shell: echo $PATH
  environment:
      PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"

- name: Test Go
  shell: go env
  environment:
      PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"

- name: Install Go dependencies
  shell: go get -u -v {{ item }}
  with_items:
    - github.com/nsf/gocode
    - github.com/tools/godep
    - github.com/golang/lint/golint
    - github.com/monochromegane/the_platinum_searcher
    - golang.org/x/tools/cmd/goimports
  environment:
      PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
      GOPATH: /home/jaredjohnston/Workspace/go
