---
- name: Tap Homebrew repositories
  homebrew_tap: name={{ item }} state=present
  with_items:
    - homebrew/cask

- name: Update and upgrade Homebrew
  shell: brew update && brew upgrade && brew cleanup

- name: Install libraries with Homebrew cask
  homebrew_cask: name={{ item }}
  with_items:
   - google-chrome
   - firefox
   - transmission
   - vlc
   - spectacle
   - dropbox
   # - maccy
   # - itsycal

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - bash
    - bash-completion
    - cask
    - coreutils
    - curl
    - git-extras
    - gnu-sed
    - the_silver_searcher
    - tmux
    - tree
    - rar
    - vcprompt
    - vim
    - wget
    - bash-completion
    - fdk-aac
    # - ffmpeg # might need to install this manually not sure if it installs with ffplay or not
    # - youtube-dl
    - jpeg
    - lame
    - openjpeg
    - opus
    - schroedinger
    - x264
    - xvid
    - direnv
    - diff-so-fancy

- name: Install openssh with Homebrew
  homebrew: name=openssh state=latest install_options=with-keychain-support

# brew tap cantino/mcfly
# brew install cantino/mcfly/mcfly
