---
- name: Make bin directory for vcprompt
  file: path=~/bin state=directory

- name: install vcprompt
  sudo: true
  get_url: url=https://github.com/djl/vcprompt/raw/master/bin/vcprompt dest=~/bin/vcprompt

# the equivalent of ` chmod 755 ~/bin/vcprompt`, see: https://docs.ansible.com/ansible/file_module.html
#- name: change permissions on file
- file: path=~/bin/vcprompt mode=0755

#- name: Change keyboard options to remap caps
-  lineinfile: dest=/etc/default/keyboard regexp=^XKBOPTIONS="" line=XKBOPTIONS="ctrl:nocaps"

- name: Reconfigure new options #is this step needed? does ubuntu do this every time it starts?
  sudo: true
  ignore_errors: yes # because there is a lock and the message says it will be done on restart
  shell: dpkg-reconfigure -phigh console-setup
# see: https://askubuntu.com/questions/149971/how-do-you-remap-a-key-to-the-caps-lock-key-in-xubuntu?answertab=votes#tab-top
# or: https://www.emacswiki.org/emacs/MovingTheCtrlKey#toc9
# see here for an alternative to scripting the key mapping operation: https://askubuntu.com/questions/158150/how-to-remap-capslock-key-to-ctrl-in-xubuntu

# I commented out the following because I had to have a global install of nodejs to use tern: https://github.com/ternjs/tern_for_vim
## part of the node.js install
## followed this guide: http://www.hostingadvice.com/how-to/install-nodejs-ubuntu-14-04/#node-version-manager
#- name: curl the install.sh
#  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash

- name: Install nodejs
  sudo: false
  # Andre de Jager reckons this is the proper way to install:
  # https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
  # TODO: test this method and install this way if I can do it without having
  # to run npm as superuser to install packages.
# TODO: turn the following into a task. Source: https://gist.github.com/isaacs/579814, or http://stackoverflow.com/questions/31025159/installing-nodejs-without-sudo-in-ubuntu
# echo 'export PATH=$HOME/local/bin:$PATH' >> ~/.bashrc
# . ~/.bashrc
# mkdir ~/local
# mkdir ~/node-latest-install
# cd ~/node-latest-install
# curl http://nodejs.org/dist/node-latest.tar.gz | tar xz --strip-components=1
# ./configure --prefix=~/local
# make install # ok, fine, this step probably takes more than 30 seconds...
# curl https://www.npmjs.org/install.sh | sh

- name: Install hist
  sudo: false
  # https://github.com/jcsalterego/historian
  # TODO: curl the raw hist file to .bin directory

- name: Install openvpn
  sudo: false
  apt: name={{ item }} state=latest
  with_items:
    # - openvpn # what else needs to be installed here? I followed this vid: https://youtu.be/rveZMU0Vg7A
  # set a password for openvpn user `passwd openvpn`
  # go to URL given for admin webserver, and log in
  # download the client.ovpn
  # open client.ovpn in vim and change the ip address to the public address of the server
  # user the client.ovpn file to set up vpn connection on other devices.
