---
- name: Make autoload directory
  file: path=~/.vim/autoload state=directory

- name: Make bundle directory
  file: path=~/.vim/bundle state=directory

- name: Make Zenburn directory
  file: path=~/.vim/colors state=directory

- name: Get Zenburn
  get_url: url=https://raw.githubusercontent.com/jnurmine/Zenburn/master/colors/zenburn.vim dest=~/.vim/colors/zenburn.vim

- name: Get Vim Plug
  get_url: url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim dest=~/.vim/autoload/plug.vim

  # - name: Clone ctrlp
  #   git: repo=https://github.com/kien/ctrlp.vim.git dest=~/.vim/bundle/ctrlp.vim

  #todo: add Flake8 - a python styling check tool
