---
- name: Make autoload directory
  file: path=~/.vim/autoload state=directory

- name: Make bundle directory
  file: path=~/.vim/bundle state=directory

- name: Make Zenburn directory
      file: path=~/.vim/colors state=directory
  
- name: Get Pathogen
  get_url: url=https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim dest=~/.vim/autoload/pathogen.vim

- name: Clone ctrlp
  git: repo=https://github.com/kien/ctrlp.vim.git dest=~/.vim/bundle/ctrlp.vim

- name: Get Zenburn
  get_url: url=https://raw.githubusercontent.com/jnurmine/Zenburn/master/colors/zenburn.vim dest=~/.vim/colors/zenburn.vim

  #todo: add Flake8 - a python styling check tool
