---
- name: Make autoload directory
  file: path=~/.vim/autoload state=directory

- name: Make bundle directory
  file: path=~/.vim/bundle state=directory

- name: Get Pathogen
  get_url: url=https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim dest=~/.vim/autoload/pathogen.vim

- name: Clone ctrlp
  git: repo=https://github.com/kien/ctrlp.vim.git dest=~/.vim/bundle/ctrlp.vim
