#!/usr/bin/expect

set timeout -1

# Check if an argument is provided
if { $argc > 0 } {
    set server [lindex $argv 0]
} else {
    set server "triton"
}

set command "source ~/user_dotfiles/jj_bashrc"

spawn ssh -t -i /tmp/triton_ed25519.pem reefatlas@$server
expect "$ "
send "$command\r"
interact
