- hosts: targets # this is a play since it is a left-most item
  gather_facts: False # disables gathering facts about the operating system, Usually these are discovered automatically by the setup module in Ansible. https://viewsby.wordpress.com/2014/11/25/ansible-disable-gather-facts/
  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/homebrew.yml
    - include: tasks/vim.yml
