- hosts: targets # this is a play since it is a left-most item
  gather_facts: False # disables gathering facts about the operating system, Usually these are discovered automatically by the setup module in Ansible. https://viewsby.wordpress.com/2014/11/25/ansible-disable-gather-facts/
  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/apt.yml
    #- include: tasks/homebrew.yml
    - include: tasks/go.yml
    #- include: tasks/emacs.yml
    - include: tasks/vim.yml

#todo: move the vcprompt comands to a different .yml file
#    - name: Create directory
#      file: path=~/bin/vcprompt state=directory
#
#    - name: install vcprompt
#      get_url: url=https://github.com/djl/vcprompt/raw/master/bin/vcprompt dest=~/bin/vcprompt
#
#    - name: set executable
#      # chmod command doesn't work, find another way to set executable
#      shell: chmod 755 ~/bin/vcprompt
#
#    - name: add vcpromtp to the path
#      #todo: add vcprompt to the path. I think in ubuntu ~/bin/ is not on the path by default but maybe in osx it is. Maybe I could get_url to a different locatio that is on the path by default? check the path then try it.
