. ~/Workspace/dotfiles/bash/env
. ~/Workspace/dotfiles/bash/config # what does this do?
. ~/Workspace/dotfiles/bash/aliases
## added by travis gem
#[ -f /Users/stuartrexking/.travis/travis.sh ] && source /Users/stuartrexking/.travis/travis.sh
#
### Added by the Heroku Toolbelt
#export PATH="/usr/local/heroku/bin:$PATH"

complete -W "$(teamocil --list)" teamocil # this file was created when installing teamocil. See http://www.teamocil.com/
